### ISSUE TITLE
When will the code be available? 

### ISSUE THREAD

**Issue by MayarOssama** [rashad101/DialoKG#1]

**Comment by rashad101** [comment]
Hi Mayar, we are currently working on cleaning the code to make it more usable and adaptable to other datasets as well. It will be made available soon. Once it is available, I will comment here gain.

**Comment by vasco95** [comment]
Any update on this?

**Comment by rashad101** [comment]
Hi, 
Thanks for you interest in our work. The code will be made available in October.
Thanks for your understanding.
